### ISSUE TITLE
Does this even works?

### ISSUE THREAD

**Issue by CurlyFlow** [Zwyk/Z-Mission-Table-Win-Estimator#2]
<img width="631" alt="1" src="https://user-images.githubusercontent.com/43281991/104812783-e9c44680-5804-11eb-902e-9ce6204ed194.png">

Or does it not work on german client?

How can i help with translating?

**Comment by Zwyk** [comment]
Spells are not supported right now in other languages than English, so the WA should only account for the base HP and Attack.
It shouldn't give you 100% win there though, could you check the "Show details" in the WA Custom Options and screen the information below ? Thanks!

If you're really willing to help for the translation for German please contact me on Discord Zwyk#5555 :)

**Comment by CurlyFlow** [comment]
<img width="1111" alt="2" src="https://user-images.githubusercontent.com/43281991/104823632-d6889980-584b-11eb-9f91-0d2ff968e502.png">


ive added u

**Comment by Zwyk** [comment]
Thanks, the issue was that German client uses comma as thousand separator, I fixed it in the [latest build on wago.io](https://wago.io/hNQkeoP-B)

I'll catch you on Discord for the German spell implementation!
